# Site settings
title: Hi, I'm Harsh Tripathi !
description: Harsh Tripathi's professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Harsh Tripathi
user_title: 
user_job_title: Student, Data Scientist, Learner
email: htripathi6 [at] gmail.com
twitter_username: htripathi06
github_username:  harshtripathi6

exclude: ['package.json', 'src' , 'node_modules']
